version: "3.7"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: always
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Spain
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: always
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Spain
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: always
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Spain
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
#  sabnzbd:
#    container_name: sabnzbd
#    image: ghcr.io/hotio/sabnzbd:latest
#    restart: always
#    logging:
#      driver: json-file
#    ports:
#      - 8080:8080
#      - 9090:9090
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Spain
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /docker/appdata/sabnzbd:/config
#      - /data/usenet:/data/usenet:rw
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: always
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Spain
    volumes:
      - /docker/appdata/prowlarr:/config
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /docker/appdata/deluge/config:/config
      - /data/torrents:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: always
